### PR TITLE
Implemented the pop_up modal.

### PR DESCRIPTION
**Pull request by kenkomu**
Implemented the pop_up modal in a new folder called pop_up in the components folder.

### CODE REVIEW

**Comment by codeWhizperer** [comment]
@kenkomu 
Screenshot 2024-03-06 at 01 02 51
could you please look into this, add types to the function. it fails on build via vercel

**Comment by kenkomu** [comment]
Okay, I am working on it.

**Comment by codeWhizperer** [comment]
@kenkomu How you initiate the pop_up, maybe share a short demo of how it work. secondly, the modal should be functional i.e able to transfer assets, you'd have to integrate with the token bound sdk. Reference the ```transferERC20```  function. 
More info here: https://tokenbound.gitbook.io/starknet-tokenbound/sdk/api-reference

Let me kmow if you need any help.

**Comment by codeWhizperer** [comment]
@kenkomu any update on this before it's assigned to someone else?

**Comment by kenkomu** [comment]
@codeWhizperer I am still working on it. I faced a blocker when implementing the functions. But it is still on a working progress.

**Comment by codeWhizperer** [comment]
@kenkomu, thank you for your valuable feedback. We are working to resolve this issue by Monday. If you need assistance, please let us know so we can schedule a call.

**Comment by kenkomu** [comment]
@codeWhizperer, I need your assistance can we have a google meet call?

**Comment by codeWhizperer** [comment]
Okay, message me on Telegram @codeWhizperer

**Comment by kenkomu** [comment]
@codeWhizperer 
[
Screenshot from 2024-03-16 18-28-23
](url)

**Comment by kenkomu** [comment]
@codeWhizperer Can finish working on this?

**Pull request closed without merging**
